travis:
  secure:
    BINSTAR_TOKEN: HsUIBjIgTHh8e+jqWirkT8ojpPOLDBgCojn1j07z65iRxtCaF+bUL0c5ScUN8OGeiRB3BtGzfdkqReM69Tqagt2/0oAFV8SJqah58MWdsvagQn9WaF2Ihzzlvtgdrp8J8cyhGzZKTIh/A/fgA05s36JfLiDpkgIbb9a2Rj8x7surxEH0xb877bBCA7EkRzNuLCElqcFN7QLJv6esV+QMG7Ei+RBI9+dxGhL4hYMNSi6ecKHwaX+jQAir0VD6psgx5h1QvUFi4PSAVPwZ27ewemjbodjQi1yWviZdMajXke6PZL3rStAb1ehLZsBVYQ8hkitihKrp126PeTCL1KBhfikjvnhJafURUAQ0mfmXn5oRZUudBpdnC7tsu9KCK50gGqWzacSHLkYW61t+QOpUP7jrfoj8LvFQ1mgErDmQloW8wra3qosKPtWcYJ1+60LtYIV8g/kw/9suPXDh5bTb89MMuuAlIQDueDPMj9e1VBAE/7+N5CUKp/HdIo7Z7a7A0+ESqA0kDZ4TIym/gXEh/MgNFZOs0g4NqwPBJ7xpZ8uPNPOhtQH1jacYKkuNtedcxd+SrAIqywoVheS+cPOMVAEUIGX31kdVoubdr3XIB+Zs7SR+rc5W0xGGlspqnT8eUEuIpp0gV/nhuzSWea8ajhJckhHb4sTzD9jvHtakohg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
